//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste3
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_livro()
        {
            this.tbl_livros_requisitados = new HashSet<tbl_livros_requisitados>();
        }
    
        public int id_livro { get; set; }
        public string autor { get; set; }
        public string autor_principal { get; set; }
        public string titulo { get; set; }
        public string editora { get; set; }
        public string edicao { get; set; }
        public string volume { get; set; }
        public int id_categoria { get; set; }
    
        public virtual tbl_categoria tbl_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_livros_requisitados> tbl_livros_requisitados { get; set; }
    }
}
