//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste3
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_cliente()
        {
            this.tbl_livros_requisitados = new HashSet<tbl_livros_requisitados>();
        }
    
        public int id_cliente { get; set; }
        public string nome { get; set; }
        public string bi { get; set; }
        public int nuit { get; set; }
        public string morada { get; set; }
        public string bairro { get; set; }
        public string telf1 { get; set; }
        public string telf2 { get; set; }
        public int id_distrito { get; set; }
    
        public virtual tbl_distrito tbl_distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_livros_requisitados> tbl_livros_requisitados { get; set; }
    }
}
