//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste3
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_livros_requisitados
    {
        public int id_livros_requisitados { get; set; }
        public string estado { get; set; }
        public string observacao { get; set; }
        public int id_cliente { get; set; }
        public int id_livro { get; set; }
    
        public virtual tbl_cliente tbl_cliente { get; set; }
        public virtual tbl_livro tbl_livro { get; set; }
    }
}
